import "./globals.css";
import { Times_New_Roman, Roboto } from "next/font/google";

const inter = Times_New_Roman({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"] });

export const metadata = {
  title: "Everest",
  description: "Generated by create next app",
  icons: {
    shortcut: "",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
